Webpack + Refactor into es6 modules
forbes/ad-inspector pull request #13
Opened 2018-04-10 22:01 UTC by lynques

- Webpack to bundle/minify js and css
- Refactor to es6 modules
- Retain existing functionality

2018-04-11 14:33 UTC, annezhou920 approved these changes

2018-04-16 17:30 UTC, mcscrambles commented on src/loader.js
> +        style[k] = Math.max(0, style[k] - padding) + 'px';
template literal

2018-04-16 17:34 UTC, mcscrambles requested changes

2018-04-16 17:34 UTC, mcscrambles commented on src/loader.js
> +    style.width = Math.min(document.width || document.body.offsetWidth, element.offsetWidth + padding * 2) + 'px';
template literal

2018-04-16 17:34 UTC, mcscrambles commented on src/loader.js
> +    style.height = Math.min(document.height || document.body.offsetHeight, element.offsetHeight + padding * 2) + 'px';
template literal

2018-04-16 17:34 UTC, mcscrambles commented on src/loader.js
> +        const keyDom = utils.dom('b', {}, {}, key + ': ');
template literal

2018-04-16 17:34 UTC, mcscrambles commented on src/slot-helper.js
> +    return 'https://www.google.com/dfp/' + account + '#delivery/' + type + 'Detail/' + type + 'Id=' + id;
template literal

2018-04-16 17:34 UTC, mcscrambles commented on src/slot-helper.js
> +            size_array.push(sizes[i].getWidth() + 'x' + sizes[i].getHeight());
template literal

2018-04-24 16:49 UTC, mcscrambles approved these changes

2018-04-24 17:10 UTC, merged