Node Version v20.11.1
forbes/ad-inspector pull request #23
Opened 2024-03-25 20:57 UTC by anastasiiasok

- Upgrade to Node Version v20.11.1
Ticket: https://forbesmedia.atlassian.net/browse/ADSS-323

2024-03-28 15:05 UTC, GevKerobyan-OP approved these changes

2024-03-28 16:00 UTC, sarahcalande requested changes
please add an .nvmrc file with the node version

2024-04-03 13:53 UTC, anastasiiasok commented
> please add an .nvmrc file with the node version

done

2024-04-03 14:03 UTC, FarahQan approved these changes

2024-04-04 13:55 UTC, mabramishvili approved these changes

2024-04-05 15:07 UTC, sarahcalande approved these changes

2024-04-09 15:02 UTC, merged